title: "Amit Thusay's Portfolio"    # Site title
author: "Amit Thusay"               # Your name
description: "Showcasing my engineering projects, skills, and experience."

# Theme
remote-theme: sighingnow/jekyll-gitbook        # Use GitBook theme

syntax_highlighter_style: colorful

# Navigation
nav:
  - title: "About Me"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Resume"
    url: "/resume/"

# Plugins
plugins:
  - jekyll-feed                     # RSS feed
  - jekyll-seo-tag                  # SEO tags
  - jekyll-sitemap                  # Sitemap generator

# Pagination
paginate: 5
paginate_path: "/page:num/"